### ISSUE TITLE
Not returning custom fields in version 6

### ISSUE THREAD

**Issue by arturludan** [pipedrive/client-php#100] opened 2023-10-05 17:35 UTC
Сustom fields are not returned when I use the getDeals()/getDeal()/getPersons()/getPerson() methods.
During debugging, I see custom fields in the response, but after deserialization, they don't get into the object.
In version 4, the fields are present.

**Comment by mattbloomfield** [comment] 2024-04-15 21:56
Same, this makes the sdk unusable for us!

**Comment by siirimangus** [comment] 2024-04-19 11:41
Hey, thank you for noticing and reporting. It seems this sadly really is the case. But I'm closing this issue as it is a duplicate of that one and keep the conversation going on there: https://github.com/pipedrive/client-php/issues/105

**Closed by siirimangus** 2024-04-19 11:41 UTC
