### ISSUE TITLE
updateAPerson and other updates don't consider custom fields

### ISSUE THREAD

**Issue by Robertkowski** [pipedrive/client-php#29] opened 2021-02-02 12:29 UTC
only this fields will be changed:
```
        $_parameters = array (
            'name'       => $this->val($options, 'name'),
            'owner_id'   => $this->val($options, 'ownerId'),
            'org_id'     => $this->val($options, 'orgId'),
            'email'    => array_values($this->val($options, 'email')),
            'phone'    => array_values($this->val($options, 'phone')),
            'visible_to' => APIHelper::prepareFormFields($this->val($options, 'visibleTo'))
        );
```

**Comment by alex-bukach** [comment] 2021-04-30 12:21
@Robertkowski looks a duplicate of https://github.com/pipedrive/client-php/issues/15. There's a pull request containing a fix.

**Comment by ziimk** [comment] 2021-08-04 09:06
Thank you for the patience and suggestions. The changes implemented in https://github.com/pipedrive/client-php/pull/48 should fix the issues with updating custom fields in deals, persons and organizations endpoints.

As mentioned above, this is a duplicate of #15 , so closing it

**Closed by ziimk** 2021-08-04 09:06 UTC
